# Generated by Django 5.1.3 on 2025-11-19 22:40

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lkup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', code='Invalid zipcode', message='Invalid postal code')])),
                ('country', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], default='Unknown', max_length=1)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('assoc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lkup.assoctype')),
                ('person_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_pri', to='prsn.person')),
                ('person_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_sec', to='prsn.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eff_from', models.DateField()),
                ('eff_thru', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prsn.address')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prsn.person')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('K1', 'Kindergarten 1'), ('K2', 'Kindergarten 2'), ('01', '1st Grade'), ('02', '2nd Grade'), ('03', '3rd Grade'), ('04', '4th Grade'), ('05', '5th Grade'), ('06', '6th Grade'), ('07', '7th Grade'), ('08', '8th Grade'), ('09', '9th Grade'), ('10', '10th Grade'), ('11', '11th Grade'), ('12', '12th Grade')], max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prsn.person')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lkup.school')),
            ],
        ),
        migrations.CreateModel(
            name='Vaguppu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('academylvl', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lkup.academylvl')),
                ('academyyr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lkup.academyyr')),
                ('delegate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delegate', to='prsn.person')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher', to='prsn.person')),
            ],
            options={
                'verbose_name': 'vaguppu',
                'verbose_name_plural': 'vaguppugal',
            },
        ),
        migrations.CreateModel(
            name='VaguppuStud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prsn.student')),
                ('vaguppu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prsn.vaguppu')),
            ],
            options={
                'verbose_name': 'vaguppu_maanavar',
                'verbose_name_plural': 'vaguppu_maanavargal',
            },
        ),
    ]
